---
version: '3'

networks:
  link-local:
    ipam:
      config:
      - subnet: 169.254.0.0/16

services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    image: 311462405659.dkr.ecr.eu-west-1.amazonaws.com/opg-digicop/web:latest
    ports:
      - 8888:80
    depends_on:
      - app
    environment:
      WEB_HOST: "app"

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: 311462405659.dkr.ecr.eu-west-1.amazonaws.com/opg-digicop/app:latest
    ports:
      - 9000:9000
    networks:
      - default
      - link-local
    depends_on:
      - dynamodb
      - postgres
      - metadata
    environment:
      DYNAMODB_ENDPOINT: http://dynamodb:8000
      DC_SYMFONY_SECRET: dc2018!
      DC_DB_HOST: postgres
      DC_DB_PORT: 5432
      DC_DB_NAME: digicop
      DC_DB_USER: digicop
      DC_DB_PASS: dcdb2018!
      DC_FIXURES_USERS: |
        email=elvis.ciotti@digital.justice.gov.uk&password=Abcd1234
        email=sean.privett@digital.justice.gov.uk&password=Abcd1234
        email=biggs.thorarensen@digital.justice.gov.uk&password=Abcd1234
        email=shaun.lizzio@digital.justice.gov.uk&password=Abcd1234
        email=robert.ford@digital.justice.gov.uk&password=Abcd1234
        email=behat@digital.justice.gov.uk&password=Abcd1234
      DC_FIXURES_CASES: |
        number=12345671&name=Peter Bloggs&type=both
        number=22345672&name=Victoria Brady&type=pa
        number=32345673&name=Thomas Jefferson&type=hw
        number=42345674&name=Susan Grindle&type=both
        number=62345676&name=Lia Shelton&type=pa
        number=72345677&name=Abdullah Lang&type=pa
        number=52345675&name=Angela Walker&type=pa
        number=92345679&name=Justine Henderson&type=pa
        number=82345678&name=Marcus Cruz&type=pa
        number=12345678&name=Behat User&type=both

  dynamodb:
    image: dwmkerr/dynamodb

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: digicop
      POSTGRES_USER: digicop
      POSTGRES_PASSWORD: dcdb2018!

  composer:
    image: composer
    volumes:
      - .:/app
    command: "composer install"

  npm:
    image: node
    working_dir: /app
    volumes:
      - .:/app
    command: "npm i --unsafe-perm"

  behat:
    image: php:7.2.7-fpm-alpine3.7
    volumes:
      - .:/app:ro
    working_dir: /app
    entrypoint: bin/behat
    command: -c tests/behat/behat.yml
    environment:
      DC_SYMFONY_SECRET: dc2018!
      DC_DB_HOST: postgres
      DC_DB_PORT: 5432
      DC_DB_NAME: digicop
      DC_DB_USER: digicop
      DC_DB_PASS: dcdb2018!
      DC_FIXURES_USERS: |
        email=behat@digital.justice.gov.uk&password=Abcd1234
      DC_FIXURES_CASES: |
        number=12345678&name=Behat User&type=both
      BEHAT_PARAMS: '{"extensions" : {"Behat\\MinkExtension" : {"base_url" : "http://web"}}}'

  phpunit:
    image: php:7.2.7-fpm-alpine3.7
    volumes:
      - .:/app:ro
    working_dir: /app
    entrypoint: bin/phpunit
    command: -c tests/phpunit
    environment:
      DC_SYMFONY_SECRET: dcphpunit2018!
      DC_DYNAMODB_KEY: key
      DC_DYNAMODB_SECRET: secret
      DC_DB_HOST: postgres
      DC_DB_PORT: 5432
      DC_DB_NAME: digicop
      DC_DB_USER: digicop
      DC_DB_PASS: dcdb2018!

  qa:
    image: jakzal/phpqa:alpine
    volumes:
      - .:/app:ro
    working_dir: /app

  metadata:
    image: bpholt/fake-ec2-metadata-service
    volumes:
      - ./docker/metadata/opt/aws:/opt/aws
    networks:
      link-local:
        ipv4_address: 169.254.169.254
