---
version: '3'

services:
  app:
    environment:
      APP_ENV: 'test'
      PANTHER_CHROME_DRIVER_BINARY: '/usr/lib/chromium/chromedriver'
      PANTHER_CHROME_BINARY: '/usr/lib/chromium/chrome'
      PANTHER_NO_SANDBOX: 1
      PANTHER_CHROME_ARGUMENTS: '--no-sandbox --ignore-certificate-errors --allow-insecure-localhost --disable-dev-shm-usage --allow-running-insecure-content'
      DC_S3_ENDPOINT: 'http://localstack:4572'
      DYNAMODB_ENDPOINT: 'http://localstack:4569'
      SIRIUS_PUBLIC_API_PASSWORD: 'FAKE_API_PASSWORD'
      AWS_ACCESS_KEY_ID: 'foo'
      AWS_SECRET_ACCESS_KEY: 'bar'
      DATABASE_URL: "sqlite:///%kernel.project_dir%/var/test.db3"
      SYMFONY_DEPRECATIONS_HELPER: 100
