# https://docs.docker.com/compose/compose-file/compose-file-v2/#environment

# ###############################################################################
# This file is owned by WebOps. Do not merge to master without WebOps input first
# ###############################################################################

version: '2.1'

services:
  frontend:
    volumes_from:
        - php
    build:
      context: frontend
      dockerfile: ../docker/Dockerfile-nginx
    ports:
        - 8888:80
    depends_on:
    # todo - healthcheck - wait for FPM to give a 9000 out
        - php
    environment:
      SYMFONY_ALLOW_DEV: 1
    volumes:
       - ./frontend/misc/config/app.conf:/etc/nginx/conf.d/app.conf

  php:
    build:
      context: frontend
      dockerfile: Dockerfile-php
    volumes:
       - ./frontend/app:/app/app:ro
       - ./src-common:/app/common:ro
       - ./frontend/src:/app/src:ro
       - ./frontend/web:/app/web:ro
       - ./frontend/vendor:/app/vendor:ro
       - ./env/local:/scripts:ro
    depends_on:
      - dynamodb
      - postgres
    environment:
      DC_SYMFONY_SECRET: dc2018!
      DC_DYNAMODB_KEY: key
      DC_DYNAMODB_SECRET: secret
      DC_DB_HOST: postgres
      DC_DB_PORT: 5432
      DC_DB_NAME: digicop
      DC_DB_USER: digicop
      DC_DB_PASS: dcdb2018!
      DC_FIXURES_USERS: |
        email=elvis.ciotti@digital.justice.gov.uk&password=Abcd1234
        email=sean.privett@digital.justice.gov.uk&password=Abcd1234
        email=biggs.thorarensen@digital.justice.gov.uk&password=Abcd1234
        email=shaun.lizzio@digital.justice.gov.uk&password=Abcd1234
        email=robert.ford@digital.justice.gov.uk&password=Abcd1234


  composer:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile-composer
    entrypoint:
        - /entrypoint.sh
    volumes:
      - ./env/local/composer.sh:/entrypoint.sh
      - ./frontend:/app:delegated
      - ~/.composer:/root/.composer:delegated

  node:
    build:
      context: ./frontend
      dockerfile: Dockerfile-node
    volumes:
      - ./env/local/frontend-setup.sh:/entrypoint-setup.sh:ro
      - ./env/local/frontend-generate.sh:/entrypoint-generate.sh:ro
      - ./frontend/package.json:/app/package.json:ro
      - ./frontend/package-lock.json:/app/package-lock.json:delegated
      - ./frontend/gulpfile.js:/app/gulpfile.js:ro
      - ./frontend/node_modules:/app/node_modules:delegated
      - ./frontend/web/assets:/app/web/assets:delegated
      - ./frontend/src:/app/src:ro

  behat:
    build:
      context: ./frontend
      dockerfile: Dockerfile-php
    depends_on:
      - frontend
    entrypoint:
        - /entrypoint.sh
    volumes:
      - ./env/local/behat.sh:/entrypoint.sh
      - ./frontend:/app:delegated
    environment:
      DC_SYMFONY_SECRET: dc2018!
      DC_DYNAMODB_KEY: key
      DC_DYNAMODB_SECRET: secret
      DC_DB_HOST: postgres
      DC_DB_PORT: 5432
      DC_DB_NAME: digicop
      DC_DB_USER: digicop
      DC_DB_PASS: dcdb2018!
      DC_FIXURES_USERS: |
        email=elvis.ciotti@digital.justice.gov.uk&password=Abcd1234
        email=sean.privett@digital.justice.gov.uk&password=Abcd1234
        email=biggs.thorarensen@digital.justice.gov.uk&password=Abcd1234
        email=shaun.lizzio@digital.justice.gov.uk&password=Abcd1234
        email=robert.ford@digital.justice.gov.uk&password=Abcd1234

  phpunit:
    build:
      context: ./frontend
      dockerfile: Dockerfile-php
    entrypoint:
        - /entrypoint.sh
    volumes:
      - ./env/local/phpunit.sh:/entrypoint.sh
      - ./frontend:/app:delegated

  dynamodb:
    # https://hub.docker.com/r/deangiberson/aws-dynamodb-local/
    image: dwmkerr/dynamodb

  postgres:
    image: postgres:9.6
    #      ports:
    #        - 5432:5432
    volumes:
    - .postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: digicop
      POSTGRES_USER: digicop
      POSTGRES_PASSWORD: dcdb2018!

  qa:
    image: jakzal/phpqa:alpine
    working_dir: /app
    volumes:
      - ./frontend:/app:delegated
