# https://docs.docker.com/compose/compose-file/compose-file-v2/#environment
version: '2'

services:
  nginx:
    container_name: dcnginx
    volumes:
       - ./frontend/app/.:/app/app
       - ./frontend/bin/.:/app/bin
       - ./frontend/web/.:/app/web
       - ./frontend/src/.:/app/src
    build:
      context: frontend
      dockerfile: Dockerfile-nginx
    ports:
        - 8082:80
    links:
        - php
#
#  php:
#    image: php:fpm-alpine
#    container_name: dc_php
#    volumes:
#       - ./frontend/.:/app
#    ports:
#       - 9000:9000
#    environment:
#      SYMFONY_ALLOW_DEV: 1

  php:
    container_name: dcphp
    build:
      context: frontend
      dockerfile: Dockerfile-php
    volumes:
       - ./frontend/app/.:/app/app
       - ./frontend/bin/.:/app/bin
       - ./frontend/web/.:/app/web
       - ./frontend/src/.:/app/src
    ports:
       - 9000:9000



#  frontend:
#    container_name: dc_frontend
#    volumes:
#      - ./frontend/.:/app
#    build:
#      context: frontend
##    image: registry.service.opg.digital/opguk/digi-deps-frontend-base
#    ports:
#        - 8082:80
#        - 443:443
#    environment:
#      OPG_NGINX_ROOT: /app/web
#      OPG_NGINX_INDEX: app_dev.php
#      SYMFONY_ALLOW_DEV: 1
#      OPG_DOCKER_TAG: latest
#      OPG_NGINX_SERVER_NAMES: localhost 127.0.0.1 router frontend admin api redisfront test digideps-client.local digideps-admin.local *.dd.opg.digital
#      OPG_NGINX_REDIRECT_SSL: 1
#      OPG_NGINX_CLIENTMAXBODYSIZE: 15M
#      OPG_NGINX_CLIENTBODYTIMEOUT: 300s
#      VIRTUAL_HOST: www
#      FRONTEND_SECRET: 123
#      FRONTEND_GA: setme

