# https://docs.docker.com/compose/compose-file/compose-file-v2/#environment
version: '2.1'

services:
  frontend:
    volumes_from:
        - php
    build:
      context: frontend
      dockerfile: Dockerfile-nginx
    depends_on:
    # todo - healthcheck - wait for FPM to give a 9000 out
        - php
    environment:
      SYMFONY_ALLOW_DEV: 1
    volumes:
       - ./frontend/misc/config/app.conf:/etc/nginx/conf.d/app.conf

  php:
    build:
      context: frontend
      dockerfile: Dockerfile-php
    volumes:
       - ./frontend/app:/app/app
       - ./frontend/src:/app/src
       - ./frontend/web:/app/web
       - ./frontend/vendor:/app/vendor:ro
       - ./env/local:/scripts:ro
    environment:
      DC_SYMFONY_SECRET: dc2018!

  api_php:
      build:
        context: ./api
        dockerfile: Dockerfile-php
      volumes:
         - ./api/app:/app/app
         - ./api/src:/app/src
         - ./api/web:/app/web
         - ./api/vendor:/app/vendor:ro
         - ./env/local:/scripts:ro
      environment:
        DC_SYMFONY_SECRET: dcapi2018!

  composer:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile-composer
    entrypoint:
        - /entrypoint.sh
    volumes:
      - ./env/ci/composer.sh:/entrypoint.sh
      - ./frontend:/app

  api_composer:
    build:
      context: ./api
      dockerfile: ../docker/Dockerfile-composer
    entrypoint:
        - /entrypoint.sh
    volumes:
      - ./env/ci/composer.sh:/entrypoint.sh
      - ./api:/app

  node:
    build:
      context: ./frontend
      dockerfile: Dockerfile-node
    volumes:
      - ./env/ci/frontend-setup.sh:/entrypoint-setup.sh:ro
      - ./env/ci/frontend-generate.sh:/entrypoint-generate.sh:ro
      - ./frontend/package.json:/app/package.json:ro
      - ./frontend/package-lock.json:/app/package-lock.json:delegated
      - ./frontend/gulpfile.js:/app/gulpfile.js:ro
      - ./frontend/node_modules:/app/node_modules:delegated
      - ./frontend/web/assets:/app/web/assets:delegated
      - ./frontend/src:/app/src:ro

  behat:
    build:
      context: ./frontend
      dockerfile: Dockerfile-php
    entrypoint:
        - /entrypoint.sh
    volumes:
      - ./env/local/behat.sh:/entrypoint.sh
      - ./frontend:/app:delegated

  phpunit:
    build:
      context: ./frontend
      dockerfile: Dockerfile-php
    entrypoint:
        - /entrypoint.sh
    volumes:
      - ./env/local/phpunit.sh:/entrypoint.sh
      - ./frontend:/app:delegated

  phpstan:
    build:
      context: ./frontend
      dockerfile: Dockerfile-php
    entrypoint:
        - /entrypoint.sh
    volumes:
      - ./env/ci/phpstan.sh:/entrypoint.sh
      - ./frontend:/app:delegated

  api_phpstan:
    build:
      context: ./frontend
      dockerfile: Dockerfile-php
    entrypoint:
        - /entrypoint.sh
    volumes:
      - ./env/ci/phpstan.sh:/entrypoint.sh
      - ./api:/app:delegated

  qa:
    image: jakzal/phpqa
    volumes:
      - ./frontend:/app:ro

  api_qa:
    image: jakzal/phpqa
    volumes:
      - ./api:/app:ro
