# https://docs.docker.com/compose/compose-file/compose-file-v2/#environment
version: '2'

services:
  nginx:
    container_name: dcnginx
    volumes:
       - ./frontend/app:/app/app
       - ./frontend/web:/app/web
       - ./frontend/src:/app/src
       - ./frontend/tests:/app/tests
    build:
      context: frontend
      dockerfile: Dockerfile-nginx
    ports:
        - 8082:80
    links:
        - php
    environment:
      SYMFONY_ALLOW_DEV: 1


  php:
    container_name: dcphp
    build:
      context: frontend
      dockerfile: Dockerfile-php
    volumes:
       - ./frontend/app:/app/app
       - ./frontend/bin:/app/bin
       - ./frontend/web:/app/web
       - ./frontend/src:/app/src
    ports:
       - 9000:9000

  test:
      container_name: dctest
      build:
        context: frontend
        dockerfile: Dockerfile-php
      volumes_from:
         - php
      volumes:
         - ./frontend/tests:/app/tests
      links:
        - php
        - nginx


