# reference https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/yaml-mapping.html
AppBundle\Entity\Client:
    type: entity
    table: "client"
    id:
      id:
        type: integer
        generator:
          strategy: AUTO
    fields:
      caseNumber:
        column: case_number
        type: string
        length: 8
        nullable: false
        unique: true
      clientName:
        column: client_name
        type: string
        length: 255
        nullable: false
      createdAt:
        column: created_at
        type: datetime
        nullable: false
    oneToMany:
      orders:
        targetEntity: Order
        mappedBy: client
        cascade: ["persist"]
