# reference https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/yaml-mapping.html
AppBundle\Entity\Deputy:
    type: entity
    table: "deputy"
    id:
      id:
        type: integer
        generator:
          strategy: AUTO
    fields:
      deputyType:
        column: deputy_type
        type: string
        length: 255
      forename:
        column: forename
        type: string
        length: 255
      surname:
        column: surname
        type: string
        length: 255
      dateOfBirth:
        column: dob
        type: date
        nullable: true
      emailAddress:
        column: email_address
        type: string
        length: 255
        nullable: true
      daytimeContactNumber:
        column: daytime_contact_number
        type: string
        length: 255
        nullable: true
      eveningContactNumber:
        column: evening_contact_number
        type: string
        length: 255
        nullable: true
      mobileContactNumber:
        column: mobile_contact_number
        type: string
        length: 255
        nullable: true
      addressLine1:
        column: address_line_1
        type: string
        length: 255
        nullable: true
      addressLine2:
        column: address_line_2
        type: string
        length: 255
        nullable: true
      addressLine3:
        column: address_line_3
        type: string
        length: 255
        nullable: true
      addressTown:
        column: address_town
        type: string
        length: 255
        nullable: true
      addressCounty:
        column: address_county
        type: string
        length: 255
        nullable: true
      addressPostcode:
        column: address_postcode
        type: string
        length: 255
        nullable: true
