# reference https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/yaml-mapping.html
AppBundle\Entity\Document:
    type: entity
    table: "document"
    id:
      id:
        type: integer
        generator:
          strategy: AUTO
    fields:
      type:
        type: string
        length: 10
        nullable: false
      fileName:
        type: string
        nullable: true
      storageReference:
        type: string
      createdAt:
        column: created_at
        type: datetime
        nullable: false
    manyToOne:
      order:
        targetEntity: Order
        inversedBy: documents
        cascade: ["persist"]
        joinColumn:
          name: order_id
          referencedColumnName: id
          onDelete: CASCADE
