# reference https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/yaml-mapping.html
AppBundle\Entity\Order:
    type: entity
    table: "dc_order"
    inheritanceType: single_table
    discriminatorColumn:
      name: type
      type: string
    discriminatorMap:
      pa:  AppBundle\Entity\OrderPa
      hw:  AppBundle\Entity\OrderHw
    id:
      id:
        type: integer
        generator:
          strategy: AUTO
    fields:
      subType:
        column: sub_type
        type: string
        length: 20
        nullable: true
      hasAssetsAboveThreshold:
        column: has_assets_above_threshold
        type: string
        length: 20
        nullable: true
      appointmentType:
        column: appointment_type
        type: string
        length: 4
        nullable: true
      createdAt:
        column: created_at
        type: datetime
        nullable: false
    manyToOne:
      client:
        targetEntity: Client
        inversedBy: orders
        cascade: ["persist"]
        joinColumn:
          name: client_id
          referencedColumnName: id
          onDelete: CASCADE
    manyToMany:
      deputies:
        targetEntity: Deputy
        cascade: ["persist"]
        joinTable:
          name: ordertype_deputy
          cascade: ["persist", "delete"]
          joinColumns:
            deputy_id:
              referencedColumnName: id
          inverseJoinColumns:
            order_type_id:
              referencedColumnName: id
              onDelete: CASCADE

