# reference https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/yaml-mapping.html
AppBundle\Entity\User:
    type: entity
    table: "dc_user"
    id:
      id:
        type: integer
        generator:
          strategy: AUTO
    fields:
      email:
        type: string
        length: 60
        nullable: false
        unique: true
      password:
        type: string
        length: 60
        nullable: false