# reference https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/yaml-mapping.html
AppBundle\Entity\Deputy:
    type: entity
    table: "deputy"
    id:
      id:
        type: integer
        generator:
          strategy: AUTO
    fields:
      orderType:
        column: order_type
        type: string
        length: 4
      appointmentType:
        column: appointment_type
        type: string
        length: 4
      deputyType:
        column: deputy_type
        type: string
        length: 4
      forename:
        column: forename
        type: string
        length: 50
      surname:
        column: surname
        type: string
        length: 50
      emailAddress:
        column: email_address
        type: string
        length: 200
      contactNumber:
        column: contact_number
        type: string
        length: 50
      emailAddress:
        column: email_address
        type: string
        length: 200
      addressLine1:
        column: address_line_1
        type: string
        length: 50
      addressLine2:
        column: address_line_2
        type: string
        length: 50
      addressLine3:
        column: address_line_3
        type: string
        length: 50
      addressCounty:
        column: address_county
        type: string
        length: 50
      addressPostcode:
        column: address_postcode
        type: string
        length: 8
      addressCountry:
        column: address_country
        type: string
        length: 50
    manyToOne:
      order:
        targetEntity: Order
        inversedBy: deputys
        cascade: ["persist", "merge"]
