Common\Entity\User:
    type: entity
    schema: public
    table: "`user`"
    id:
      id:
        type: integer
        generator:
          strategy: AUTO
    fields:
      email:
        type: string
        length: 60
        nullable: false
        unique: true
      password:
        type: string
        length: 60
        nullable: false