imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }



# Twig Configuration


# Swiftmailer Configuration


services:
    # Logtash formatter for Kibana





doctrine_migrations:


# needed for dynamodb

