imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    translator:      { fallback: "en" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:
        enabled: true
        enable_annotations: true
        strict_email: true
    templating:
        engines: ['twig']
    default_locale:  "en"
    session:
      name: digideps
      handler_id: dynamo_session_handler
      # force session usage, no cookie (we want to logout when the browser closes)
      cookie_lifetime: 0
      gc_probability: 1
      gc_divisor: 100
      # session timeout (when GC kicks in)
      gc_maxlifetime: 3900
      # true:  cookie won't be accessible by Javascript, safer for XSS
      cookie_httponly: true
      # set to true when moved to HTTPS
      cookie_secure: false
    fragments:       ~
    http_method_override: true
    serializer:
      enable_annotations: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
      version_app: "%env(APP_VERSION)%"
      version_web: "%env(WEB_VERSION)%"
      version_infra: "%env(INFRA_VERSION)%"

# Swiftmailer Configuration
swiftmailer:
    transport: smtp
    host:      localhost
    username:  ~
    password:  ~
    spool:     { type: memory }

services:
    # Logtash formatter for Kibana
    logstash_formatter:
        class: Monolog\Formatter\LogstashFormatter
        arguments: [ "digicop.frontend", null, null, "", 1 ]
    line_formatter:
        class: Monolog\Formatter\LineFormatter

monolog:
   handlers:
       php_stderr:
           type: stream
           path: php://stderr
           # change on the fly as needed during development
           level: warning
           # change on the fly as needed during development
           # channels: [ "!translation" ]


# http://symfony.com/doc/master/bundles/DoctrineBundle/configuration.html
doctrine:
  dbal:
    driver:   pdo_pgsql
    host:     "%env(DC_DB_HOST)%"
    port:     "%env(DC_DB_PORT)%"
    dbname:   "%env(DC_DB_NAME)%"
    user:     "%env(DC_DB_USER)%"
    password: "%env(DC_DB_PASS)%"
    charset:  UTF8
      #options:
    #sslmode: require
  orm:
    auto_generate_proxy_classes: "%kernel.debug%"
    proxy_dir:   "%kernel.cache_dir%/doctrine/orm/Proxies"
    auto_mapping: false
    mappings:
      commonEntities:
        type: yml
        dir: "%kernel.root_dir%/config/doctrine"
        prefix: AppBundle\Entity
        is_bundle: false
    dql:
      string_functions:
        cast_as_integer: Common\Query\CastAsInteger
        str_to_date: DoctrineExtensions\Query\Postgresql\StrToDate
        to_date: DoctrineExtensions\Query\Postgresql\DateFormat
      numeric_functions:
      datetime_functions:
    #        metadata_cache_driver: apcu

doctrine_migrations:
    dir_name: "%kernel.root_dir%/config/doctrine/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations
    organize_migrations: false # Version >=1.2 Possible values are: "BY_YEAR", "BY_YEAR_AND_MONTH", false

# needed for dynamodb
# https://github.com/aws/aws-sdk-php-symfony#sample-yml-configuration
aws:
    version: latest
    region: eu-west-1
    DynamoDb:
        region: eu-west-1
