imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }
    ide: 'phpstorm://open?file=%%f&line=%%l'

web_profiler:
    toolbar: true
    intercept_redirects: false



