# env vars set by docker-compose at runtime
parameters:
    secret:   '%env(DC_SYMFONY_SECRET)%'
    env(DC_DB_HOST): ""
    env(DC_DB_PORT): ""
    env(DC_DB_NAME): ""
    env(DC_DB_USER): ""
    env(DC_DB_PASS): ""

    # allow environment override, but set sensible default
    env(DYNAMODB_ENDPOINT): https://dynamodb.eu-west-1.amazonaws.com:443
    # appended to CSS and JS as "?v=<this value>". If empty, the request timestamp will be used
    env(DC_ASSETS_VERSION): ""
