# env vars set by docker-compose at runtime
parameters:
    secret:   '%env(DC_SYMFONY_SECRET)%'
    database_host: '%env(DC_DB_HOST)%'
    database_port: '%env(DC_DB_PORT)%'
    database_name: '%env(DC_DB_NAME)%'
    database_user: '%env(DC_DB_USER)%'
    database_password:  '%env(DC_DB_PASS)%'

    # allow environment override, but set sensible default
    env(DYNAMODB_ENDPOINT): https://dynamodb.eu-west-1.amazonaws.com:443

    #    S3 Bucket configuration
    s3_bucket_name: not set
    s3_client_params:
        version: latest
        region: eu-west-1
        endpoint: 'http://fakes3:4569'
        validate: false
        credentials:
            key: 'YOUR_ACCESS_KEY_ID'
            secret: 'YOUR_SECRET_ACCESS_KEY'
    file_scanner_url: https://file-scanner-api:8443
    file_scanner_sslverify: false
