# env vars set by docker-compose at runtime
parameters:
    secret:   '%env(DC_SYMFONY_SECRET)%'
    dynamodb_key:  '%env(DC_DYNAMODB_KEY)%'
    dynamodb_secret:  '%env(DC_DYNAMODB_SECRET)%'
    database_host: '%env(DC_DB_HOST)%'
    database_port: '%env(DC_DB_PORT)%'
    database_name: '%env(DC_DB_NAME)%'
    database_user: '%env(DC_DB_USER)%'
    database_password:  '%env(DC_DB_PASS)%'
