services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Doctrine\ORM\EntityManager: "@doctrine.orm.entity_manager"

    AppBundle\DataFixtures\DefaultFixtures: ~
    AppBundle\Controller\IndexController: ~
    AppBundle\Controller\UserController: ~
    AppBundle\Controller\CaseController: ~
    AppBundle\Controller\ManageController: ~
    AppBundle\Controller\OrderController: ~
    AppBundle\Controller\DeputyController: ~
    AppBundle\Controller\DocumentController: ~
    AppBundle\Controller\BehatController: ~
    AppBundle\Controller\CsvController: ~

    AppBundle\Service\ClientService: ~
    AppBundle\Service\CsvImporterService: ~
    AppBundle\Service\OrderService: ~

    AppBundle\Service\DeputyService: ~
    AppBundle\Service\DocumentService: ~
    AppBundle\Service\SiriusService: ~

    AppBundle\Service\SiriusClient:
        class: AppBundle\Service\SiriusClient
        arguments:
            [
              base_uri: "%env(DC_SIRIUS_URL)%",
              verify: 0,
              proxy: "",
              debug: "false",
              headers:
                  Content-Type: multipart-form-data,
              version: "1.1",
              timeout: 10,
              allow_redirects: "false"
            ]

    # twig extensions
    AppBundle\Twig\AssetsExtension:
        arguments: [ "/assets/", "%env(DC_ASSETS_VERSION)%" ]
        tags:
            - { name: twig.extension }

    AppBundle\Twig\DebugExtension:
      tags:
      - { name: twig.extension }


    # Dynamo Db (session) config
    Aws\DynamoDb\DynamoDbClient:
        arguments:
            - region: 'eu-west-1'
              version: 'latest'
              validate: true
              endpoint: "%env(DYNAMODB_ENDPOINT)%"
              debug: false

    Common\SessionConnectionCreatingTable:
       arguments:
         $config:
            table_name: 'sessions'
            hash_key: 'id'
            max_lock_wait_time: 10
            min_lock_retry_microtime: 500
            max_lock_retry_microtime: 5000

    dynamo_session_handler:
      class: Aws\DynamoDb\SessionHandler
      arguments: [ "@Common\\SessionConnectionCreatingTable" ]

    Aws\DynamoDb\SessionConnectionInterface: "@Common\\SessionConnectionCreatingTable"

    AppBundle\Service\S3Client:
      arguments: [ "%env(DC_S3_REGION)%", "%env(DC_S3_ENDPOINT)%" ]

    # document storage and checking
    Aws\S3\S3ClientInterface: "@AppBundle\\Service\\S3Client"

    AppBundle\Service\File\Storage\S3Storage:
      arguments:
        $s3Client: "@AppBundle\\Service\\S3Client"
        $localBucketName: "%env(DC_S3_BUCKET_NAME)%"
        $remoteBucketName: "%env(SIRIUS_S3_BUCKET_NAME)%"

    AppBundle\Service\File\Storage\StorageInterface: "@AppBundle\\Service\\File\\Storage\\S3Storage"
    AppBundle\Service\File\Checker\ClamAVChecker: ~
    AppBundle\Service\File\Checker\PdfChecker: ~
    AppBundle\Service\File\Checker\JpgChecker: ~
    AppBundle\Service\File\Checker\PngChecker: ~
    AppBundle\Service\File\Checker\FileCheckerFactory: ~
    AppBundle\Service\File\FileUploader: ~
    AppBundle\Service\File\Types\Pdf: ~
    AppBundle\Service\File\Types\Jpg: ~
    AppBundle\Service\File\Types\Png: ~


    GuzzleHttp\Client:
      class: GuzzleHttp\Client
      arguments:
        $config:
          base_uri: "https://file-scanner-api:8443"
          verify: false
          proxy: ""
          debug: false
          headers:
            Content-Type: multipart-form-data
          version: "1.1"
          timeout: 10
          allow_redirects: false

    GuzzleHttp\ClientInterface: "@GuzzleHttp\\Client"
