services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false


    Doctrine\ORM\EntityManager:
      alias: doctrine.orm.entity_manager
      public: true

    AppBundle\DataFixtures\DefaultFixtures: ~
    AppBundle\Controller\IndexController: ~
    AppBundle\Controller\UserController: ~
    AppBundle\Controller\CaseController: ~
    AppBundle\Controller\ManageController: ~
    AppBundle\Controller\OrderController: ~
    AppBundle\Controller\DeputyController: ~
    AppBundle\Controller\DocumentController: ~

    AppBundle\Service\OrderService: ~
    AppBundle\Service\DeputyService: ~

    twig.assets_extension:
        class: AppBundle\Twig\AssetsExtension
        public: false
        arguments: [  "%kernel.root_dir%" ]
        tags:
            - { name: twig.extension }

# https://github.com/symfony/symfony/issues/15259
    aws_dynamo.client:
        class: Aws\DynamoDb\DynamoDbClient
        arguments:
            -
              credentials:
                  key: "%dynamodb_key%"
                  secret: "%dynamodb_secret%"
              region: 'eu-west-1'
              version: 'latest'
              validate: false
              endpoint: "http://%dynamodb_host%:%dynamodb_port%"
              debug: false

    aws_dynamo.session:
       class: Common\SessionConnectionCreatingTable
       arguments:
           - "@aws_dynamo.client"
           -
            table_name: 'sessions'
            hash_key: 'id'
            max_lock_wait_time: 10
            min_lock_retry_microtime: 500
            max_lock_retry_microtime: 5000

    dynamo_session_handler:
      class: Aws\DynamoDb\SessionHandler
      arguments: [ "@aws_dynamo.session" ]


    Aws\DynamoDb\SessionConnectionInterface:
       alias: aws_dynamo.session
       public: true
