version: 2
jobs:
  test:
    machine:
      image: "circleci/classic:201808-01"
    steps:
      - checkout
      - restore_cache:
          keys:
            - vendor-{{ checksum "composer.lock" }}
      - restore_cache:
          keys:
            - node_modules-{{ checksum "yarn.lock" }}
      - run:
          name: Build Dependencies
          command: |
            pip install --quiet awscli
            pyenv rehash

            # Create the s3 buckets
            # & wait for the server to become available

            docker-compose up -d localstack
            docker-compose run --rm waitforit -address=http://localstack:4572 -debug
            docker-compose run --rm aws --endpoint-url=http://localstack:4572 s3 mb s3://sirius_test_bucket
            docker-compose run --rm aws --endpoint-url=http://localstack:4572 s3 mb s3://test_bucket

            # Create dynamodb tables
            docker-compose run --rm aws --region eu-west-1 --endpoint-url=http://localstack:4569 dynamodb create-table --cli-input-json file://attempts_table.json
            docker-compose run --rm aws --region eu-west-1 --endpoint-url=http://localstack:4569 dynamodb create-table --cli-input-json file://sessions_table.json

            # Triggers Symfony Flex to run recipes during composer install - required for phpunit-bridge
            rm -rf vendor
            rm -rf symfony.lock

            # Vendor php dependencies
            docker-compose run --rm composer

            # Removes boilerplate feature test added during Symfony Flex recipe for behat
            rm -rf features/demo.feature

            # Install js dependencies
            docker-compose run --rm yarn install

            # Generate static assets
            docker-compose run --rm yarn build-dev

            # Tests
            docker-compose exec -e APP_ENV=test project_app php bin/console doctrine:schema:create
            docker-compose exec -e APP_ENV=test project_app php bin/phpunit --verbose tests
      - save_cache:
          key: vendor-{{ checksum "composer.lock" }}
          paths:
          - vendor
      - save_cache:
          key: node_modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
#      - run:
#          name: Unit Test
#          command: |
#            ./generate_certs.sh
#            docker-compose -f docker-compose.test.yml -f docker-compose.yml up -d --build --remove-orphans loadbalancer
#            docker-compose run --rm waitforit -address=tcp://loadbalancer:443 -debug -timeout 120
#            docker-compose run --rm waitforit -address=tcp://postgres:5432 -debug
#            docker-compose run --rm app php bin/phpunit --verbose tests
      - run:
          name: Integration Test
          command: |
            ./generate_certs.sh
            docker-compose up --build -d loadbalancer
            docker-compose run --rm waitforit -address=tcp://loadbalancer:443 -debug -timeout 120
            docker-compose run --rm waitforit -address=tcp://postgres:5432 -debug
            docker-compose run --rm app php bin/console doctrine:fixtures:load --group=behatTests --purge-with-truncate --no-interaction
            docker-compose run --rm behat --suite=local
      - store_test_results:
          path: ./tests/artifacts
      - store_artifacts:
          path: /tmp/behat

  build:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
          - d5:8c:8f:b5:22:91:45:16:35:49:42:f2:2e:78:a0:5f
      - checkout
      - run:
          name: Build
          command: |
            # Vendor php dependencies
            docker-compose run --rm composer
            # install js dependencies
            docker-compose run --rm yarn install
            # Generate static assets
            docker-compose run --rm yarn build
            # Build app
            docker-compose build web
            docker-compose build app
      - run:
          name: Deploy
          command: |
            git tag $CIRCLE_BUILD_NUM
            git push --tags

            docker images
            ./docker_login.sh
            docker-compose push app
            docker tag 311462405659.dkr.ecr.eu-west-1.amazonaws.com/serve-opg/app:latest 311462405659.dkr.ecr.eu-west-1.amazonaws.com/serve-opg/app:$CIRCLE_BUILD_NUM
            docker push 311462405659.dkr.ecr.eu-west-1.amazonaws.com/serve-opg/app:$CIRCLE_BUILD_NUM

            docker-compose push web
            docker tag 311462405659.dkr.ecr.eu-west-1.amazonaws.com/serve-opg/web:latest 311462405659.dkr.ecr.eu-west-1.amazonaws.com/serve-opg/web:$CIRCLE_BUILD_NUM
            docker push 311462405659.dkr.ecr.eu-west-1.amazonaws.com/serve-opg/web:$CIRCLE_BUILD_NUM
            curl --silent --show-error --fail -X POST "https://circleci.com/api/v1.1/project/github/ministryofjustice/serve-opg-infrastructure/build?circle-token=${CIRCLE_API_TOKEN}"


workflows:
  version: 2
  build:
    jobs:
    - test:
        filters:
          branches:
            ignore:
            - master
    - build:
        filters:
          branches:
            only:
            - master
