version: 2
jobs:
  test:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-v1
      - run:
          name: Build Dependencies
          command: |
            # Vendor php dependencies
            docker-compose run --rm composer
            # Generate static assets
            docker-compose run --rm npm
      - save_cache:
          key: dependencies-v1
          paths:
          - vendor
          - node_modules
          - bin
      - run:
          name: Unit Test
          command: |
            docker-compose run --rm phpunit
      - run:
          name: Integration Test
          command: |
            ./generate_certs.sh
            docker-compose up --build -d loadbalancer
            docker-compose run --rm waitforit -address=tcp://loadbalancer:443 -debug
            docker-compose run --rm app php app/console doctrine:fixtures:load --append
            docker-compose run --rm behat

  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build
          command: |
            # Vendor php dependencies
            docker-compose run --rm composer
            # Generate static assets
            docker-compose run --rm npm
            # Build app
            docker-compose build web
            docker-compose build app
      - run:
          name: Deploy
          command: |
            docker images
            ./docker_login.sh
            docker-compose push app
            docker-compose push web

workflows:
  version: 2
  build:
    jobs:
    - test:
        filters:
          branches:
            ignore:
            - master
    - build:
        filters:
          branches:
            only:
            - master
