version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build Docker-compose file
          command: |
            # Get the spruce tool (https://github.com/geofffranks/spruce) so that
            # We can remove the metadata service
            wget https://github.com/geofffranks/spruce/releases/download/v1.18.1/spruce-linux-amd64 -O  ~/bin/spruce
            chmod +x ~/bin/spruce
            spruce merge docker-compose.yml ci.spruce.yml > docker-compose.yaml
            mv docker-compose.yaml docker-compose.yml
      - run:
          name: Build
          command: |
            # Vendor php dependencies
            docker-compose run --rm composer
            # Generate static assets
            docker-compose run --rm npm
            # Build app
            docker-compose up -d --build web
      - run:
          name: Migrate Database
          command: |
            sleep 10
            docker-compose run --rm app php app/console doctrine:schema:update --force
      - run:
          name: Warm App
          command: |
            curl http://localhost:8888 -s
            curl http://localhost:8888 -s
      - run:
          name: Test
          command: |
            docker-compose run --rm phpunit
            docker-compose run --rm app php app/console doctrine:fixtures:load --append
            # docker-compose run --rm behat
      - run:
          name: Deploy
          command: |
            docker images
            ./docker_login.sh
            docker-compose push app
            docker-compose push web
