services:
    _defaults:
        autowire: true
        autoconfigure: true

    alphagov.notifications.client:
        class: Alphagov\Notifications\Client
        arguments:
            $config:
                # API key must be a <whatever>-<4 UUID>-<4 UUID> with valid Version 4 UUID JSON webtoken or an execption is thrown
                apiKey: "mock-0b6deb72-13ec-45f5-b598-88c7be007000-0b6deb72-13ec-45f5-b598-88c7be007000"
                baseUrl: "%env(DC_NOTIFY_MOCK_ENDPOINT)%"
                httpClient: "@notificationHttpClient"
