# src/AppBundle/Resources/config/validation.yml
AppBundle\Entity\Order:
  properties:
    hasAssetsAboveThreshold:
    - Type: string
    - NotBlank:
        message: "Please choose 'Yes' or 'No'"
        groups: [order-has-assets]
    subType:
    - Type: string
    - NotBlank:
        message: "Please choose the order subtype"
        groups: [order-subtype]
    appointmentType:
    - Type: string
    - NotBlank:
        message: "Please choose the appointment type"
        groups: [appointment-type]


AppBundle\Entity\Deputy:
    properties:
        deputyType:
            - Type: string
            - NotBlank:
                message: "Please select a deputy type"
                groups: [order-deputy]
        organisationName:
            - Type: string
            - NotBlank:
                message: "Please enter the deputy's organisation name"
                groups: [order-org-deputy]
        correspondenceName:
            - Type: string
            - NotBlank:
                message: "Please enter a correspondence name"
                groups: [order-org-deputy]
        forename:
            - Type: string
            - NotBlank:
                message: "Please enter the deputy's first name"
                groups: [order-deputy]
        surname:
            - Type: string
            - NotBlank:
                message: "Please enter the deputy's surname"
                groups: [order-deputy]
        dateOfBirth:
            - Type: Date
            - Date:
                groups: [order-deputy]
        emailAddress:
            - Type: string
#            - NotBlank:
#                message: "Please enter the deputy's email address"
#                groups: [order-deputy]
            - Email:
                message: The email {{ value }} is not a valid email.
                groups: [order-deputy]
            - Length:
                max: 60
                maxMessage: "The deputy's email address is too long"
                min: 7
                minMessage: "The deputy's email address is too short"
                groups: [order-deputy]
        daytimeContactNumber:
            - Type: string
            - Length:
                max: 20
                maxMessage: "The deputy's daytime contact number is too long"
                min: 10
                minMessage: "The deputy's daytime contact number is too short"
                groups: [order-deputy]
        eveningContactNumber:
            - Type: string
            - Length:
                max: 20
                maxMessage: "The deputy's evening contact number is too long"
                min: 10
                minMessage: "The deputy's evening contact number is too short"
                groups: [order-deputy]
        mobileContactNumber:
            - Type: string
            - Length:
                max: 20
                maxMessage: "The deputy's mobile number is too long"
                min: 10
                minMessage: "The deputy's mobile number is too short"
                groups: [order-deputy]
        addressLine1:
            - Type: string
#            - NotBlank:
#                message: "Please enter the deputy's address line 1"
#                groups: [order-deputy]
        addressLine2:
            - Type: string
#            - NotBlank:
#                message: "Please enter the deputy's address line 2"
#                groups: [order-deputy]
        addressLine3:
            - Type: string
#            - NotBlank:
#                message: "Please enter the deputy's address line 3"
#                groups: [order-deputy]
        addressTown:
            - Type: string
#            - NotBlank:
#                message: "Please enter a town for the deputy's address"
#                groups: [order-deputy]
        addressCounty:
            - Type: string
#            - NotBlank:
#                message: "Please enter a county for the deputy's address"
#                groups: [order-deputy]
        addressPostcode:
            - Type: string
#            - NotBlank:
#                message: "Please enter a postcode for the deputy's address"
#                groups: [order-deputy]
            - Length:
                min: 2
                minMessage: "The deputy's postcode is too short"
                max: 10
                maxMessage: "The deputy's postcode is too long"
                groups: [order-deputy]
