imports:
    - { resource: config.yml }

monolog:
   handlers:
       log_stash_prod:
           type: stream
           path: "/tmp/app-logs/application.log"
           level: warning
           formatter: logstash_formatter
