imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    translator:      { fallback: "en" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    validation:
        enabled: true
        enable_annotations: true
    trusted_proxies: ~
    session: ~
    fragments:       ~
    http_method_override: true
    serializer:
          enable_annotations: true

services:
    # Logtash formatter for Kibana
    logstash_formatter:
        class: Monolog\Formatter\LogstashFormatter
        arguments: [ "digicop.api", null, null, "", 1 ]
    line_formatter:
        class: Monolog\Formatter\LineFormatter

monolog:
   handlers:
       php_stderr:
           type: stream
           path: php://stderr
           # change on the fly as needed during development
           level: warning
           # change on the fly as needed during development
           # channels: [ "!translation" ]

# http://symfony.com/doc/master/bundles/DoctrineBundle/configuration.html
doctrine:
    dbal:
        driver:   pdo_pgsql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        #options:
            #sslmode: require

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        mappings:
          AppBundle: ~
#        metadata_cache_driver: apcu
#        proxy_dir:                    "%kernel.cache_dir%/doctrine/orm/Proxies"
        auto_generate_proxy_classes:  true
