services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

#    AppBundle\Controller\UserController:
#        public: true

    kernel.listener.jsonResponseConverter:
        class: AppBundle\EventListener\JsonResponseConverter
        arguments: [ "@serializer" ]
        public: false
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView }
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    em:
        alias: doctrine.orm.entity_manager
        public: true

    AppBundle\DataFixtures\DefaultFixtures: ~


