imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:
        enabled: true
        enable_annotations: true
        strict_email: true
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
      name: digideps
      # force session usage, no cookie (we want to logout when the browser closes)
      cookie_lifetime: 0
      gc_probability: 1
      gc_divisor: 100
      # session timeout (when GC kicks in)
      gc_maxlifetime: %session_expire_seconds%
      # true:  cookie won't be accessible by Javascript, safer for XSS
      cookie_httponly: true
      # set this only HTTPS environments to force cookie only to be sent over HTTPS (when true, login won't work on non-HTTPS domains)
      cookie_secure: %session_cookie_secure%
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    globals:
        ga: %ga%
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Swiftmailer Configuration
swiftmailer:
    transport: smtp
    host:      localhost
    username:  ~
    password:  ~
    spool:     { type: memory }

services:
    # Logtash formatter for Kibana
    logstash_formatter:
        class: Monolog\Formatter\LogstashFormatter
        arguments: [ "application.client", null, null, "", 1 ]
    line_formatter:
        class: Monolog\Formatter\LineFormatter

monolog:
   handlers:
       php_stderr:
           type: stream
           path: php://stderr
           # change on the fly as needed during development
           level: warning
           # change on the fly as needed during development
           # channels: [ "!translation" ]
