# https://symfony.com/doc/current/security.html
security:
    providers:
      our_db_provider:
        entity:
          class: AppBundle\Entity\User
          property: email
    encoders:
          AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12
    firewalls:
      main:
        anonymous: ~
        form_login:
            login_path: login
            check_path: login
            default_target_path: dashboard
        logout:
            path:   /logout
            target: login
      dev:
        pattern:  ^/(_(profiler|wdt)|css|images|js)/
        security: false

    access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/manage/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/dashboard, roles: ROLE_USER }
    - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }


#        dev:
#            pattern:  ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        login:
#            pattern:  ^/login$
#            security: false
#
#        manageController:
#            pattern:  ^/manage/*
#            security: false
#
#        secured_area:
#            form_login:
#                login_path: /login
#            logout:
#                path:   /logout
#                target: /
#                invalidate_session: false
#            anonymous: ~
#            switch_user: true
#
#    access_control:
#        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/manage, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/terms, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/privacy, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/elements, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/$ , roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        # all the rest needs authentication
#        - { path: ^/ , roles: IS_AUTHENTICATED_FULLY }
#
