services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    AppBundle\Controller\UserController:
        public: true

    twig.assets_extension:
        class: AppBundle\Twig\AssetsExtension
        public: false
        arguments: [  "%kernel.root_dir%" ]
        tags:
            - { name: twig.extension }