services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    AppBundle\Controller\UserController:
        public: true

    twig.assets_extension:
        class: AppBundle\Twig\AssetsExtension
        public: false
        arguments: [  "%kernel.root_dir%" ]
        tags:
            - { name: twig.extension }

# https://github.com/symfony/symfony/issues/15259
    aws_dynamo.client:
        class: Aws\DynamoDb\DynamoDbClient
        factory_class: Aws\DynamoDb\DynamoDbClient
        factory_method: 'factory'
        arguments:
            -
              credentials:
                  key: "%dynamodb_key%"
                  secret: "%dynamodb_secret%"
              region: 'us-west-2'
              version: 'latest'
              validate: false
              #scheme: 'https'
              endpoint: 'http://dynamodb:8000'
              debug: false

    # https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/service_dynamodb-session-handler.html
    aws_dynamo.session:
       class: Aws\DynamoDb\LockingSessionConnection
       arguments:
           - "@aws_dynamo.client"
           -
            table_name: 'sessions'
            hash_key: 'id'
            max_lock_wait_time: 10
            min_lock_retry_microtime: 500
            max_lock_retry_microtime: 5000

    dynamo_session_handler:
      class: Aws\DynamoDb\SessionHandler
      arguments: [ "@aws_dynamo.session" ]
