twig:
  debug:            "%kernel.debug%"
  strict_variables: "%kernel.debug%"
  globals:
    version_app: "%env(APP_VERSION)%"
    version_web: "%env(WEB_VERSION)%"
    version_infra: "%env(INFRA_VERSION)%"
    gtm: "%env(DC_GTM)%"
    session_expires_seconds: "%session_expire_seconds%"
    session_popup_show_after: "%session_popup_show_after%"