# reference https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/yaml-mapping.html
App\Entity\Order:
    type: entity
    repositoryClass: App\Repository\OrderRepository
    table: "dc_order"
    inheritanceType: single_table
    discriminatorColumn:
      name: type
      type: string
    discriminatorMap:
      PF:  App\Entity\OrderPf
      HW:  App\Entity\OrderHw
    id:
      id:
        type: integer
        generator:
          strategy: AUTO
    fields:
      subType:
        column: sub_type
        type: string
        length: 50
        nullable: true
      hasAssetsAboveThreshold:
        column: has_assets_above_threshold
        type: string
        length: 50
        nullable: true
      appointmentType:
        column: appointment_type
        type: string
        length: 50
        nullable: true
      createdAt:
        column: created_at
        type: datetime
        nullable: false
      madeAt:
        column: made_at
        type: datetime
        nullable: false
        options:
          default: 01-01-2017
      payloadServed:
        column: payload_served
        type: json_array
        nullable: true
      apiResponse:
        column: api_response
        type: json_array
        nullable: true
      issuedAt:
        column: issued_at
        type: datetime
        # TODO set to false later on, to avoid local failure as orders are already created.
        # A reason to introduce migrations maybe ?
        nullable: true
      servedAt:
        column: served_at
        type: datetime
        nullable: true
    manyToOne:
      client:
        targetEntity: Client
        inversedBy: orders
        cascade: ["persist"]
        joinColumn:
          name: client_id
          referencedColumnName: id
          onDelete: CASCADE
    manyToMany:
      deputies:
        targetEntity: Deputy
        cascade: ["persist"]
        joinTable:
          name: ordertype_deputy
          cascade: ["persist", "delete"]
          joinColumns:
            deputy_id:
              referencedColumnName: id
              onDelete: CASCADE
          inverseJoinColumns:
            order_type_id:
              referencedColumnName: id
              onDelete: CASCADE
    oneToMany:
      documents:
        targetEntity: Document
        mappedBy: order
        cascade: ["persist"]
