# reference https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/yaml-mapping.html
App\Entity\User:
    type: entity
    repositoryClass: App\Repository\UserRepository
    table: "dc_user"
    id:
      id:
        type: integer
        generator:
          strategy: AUTO
    lifecycleCallbacks:
      prePersist: [onPrePersist]
    fields:
      email:
        type: string
        length: 255
        nullable: false
        unique: true
      password:
        type: string
        length: 255
        nullable: false
      #sha1. 40 chars enough
      activationToken:
        type: string
        length: 40
        nullable: true
        column: activation_token
      activationTokenCreatedAt:
        type: datetime
        nullable: true
        column: activation_token_created_at
      createdAt:
        type: datetime
        nullable: true
        column: created_at
      lastLoginAt:
        type: datetime
        nullable: true
        column: last_login_at

